apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecraftadmin-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecraftadmin-8
  template:
    metadata:
      labels:
        app: kubecraftadmin-8
        kubecraft: "true"
    spec:
      containers:
      - name: kubecraftadmin-8
        image: quay-registry-quay-quay.apps.rosa.rosa-hcp-1544.kfnj.p3.openshiftapps.com/skitamura-quay-org/kubecraftadmin-8-develop/kubecraftadmin-8:latest 
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: ns-env
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: "/.kube"
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig
      serviceAccountName: kubecraftadmin-8-sa
