apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-github-kubeconfig
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target: # ExternalSecret から作成されるKubernetes Secretを指定する
    name: kubeconfig
  data: # 取得する秘匿情報を指定する
  - secretKey: config # 作成するSecretのkeyを指定
    remoteRef:
      key: kubeconfig # AWS Secrets Managerに登録>したシークレット名
